# Generated by Django 2.0.2 on 2018-05-09 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeMod1', models.FloatField(verbose_name='Nota Módulo 1')),
                ('gradeMod2', models.FloatField(verbose_name='Nota Módulo 2')),
                ('gradeSub', models.FloatField(verbose_name='Nota Substitutiva')),
                ('examClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_exams', to='core.Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_exams', to='core.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(blank=True, max_length=255, null=True, verbose_name='Arquivo')),
                ('grade', models.FloatField(verbose_name='Nota')),
                ('hours', models.IntegerField(verbose_name='Horas')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_students', to='core.Person')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_students', to='core.Task')),
            ],
        ),
    ]
