# Generated by Django 2.0.2 on 2018-05-03 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('examMod1', models.DateField(verbose_name='Prova Módulo 1')),
                ('examMod2', models.DateField(verbose_name='Prova Módulo 2')),
                ('examSub', models.DateField(verbose_name='Prova Substitutiva')),
                ('code', models.CharField(blank=True, max_length=45, verbose_name='Código')),
                ('room', models.CharField(blank=True, max_length=20, verbose_name='Sala')),
                ('weekDay', models.CharField(choices=[('SEGUNDA', 'Segunda-Feira'), ('TERCA', 'Terça-Feira'), ('QUARTA', 'Quarta-Feira'), ('QUINTA', 'Quinta-Feira'), ('SEXTA', 'Sexta-Feira'), ('SABADO', 'Sábado')], default='SEGUNDA', max_length=20, verbose_name='Dia da Semana')),
                ('horario', models.TimeField(blank=True, default='', verbose_name='Horário')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255, verbose_name='Nome')),
                ('lastName', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('ra', models.CharField(max_length=20, unique=True, verbose_name='RA')),
                ('password', models.CharField(max_length=55, verbose_name='Senha')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='É da equipe?')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['firstName', 'lastName'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data de Vencimento')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('file', models.FileField(blank=True, null=True, upload_to='arquivos', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('type', models.CharField(choices=[('P', 'Pessoal'), ('F', 'Faculdade')], max_length=1, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Entrega',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='idTaskType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Task_Type'),
        ),
        migrations.AddField(
            model_name='task',
            name='taskClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.Class'),
        ),
    ]
