# Generated by Django 2.0.2 on 2018-03-23 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('examMod1', models.DateField(verbose_name='Prova Módulo 1')),
                ('examMod2', models.DateField(verbose_name='Prova Módulo 2')),
                ('examSub', models.DateField(verbose_name='Prova Substitutiva')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data de Vencimento')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('file', models.FileField(blank=True, null=True, upload_to='arquivos', verbose_name='Arquivo')),
                ('idClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Class')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('type', models.CharField(choices=[('P', 'Pessoal'), ('F', 'Faculdade')], max_length=1, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Entrega',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255, verbose_name='Nome')),
                ('lastName', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('ra', models.CharField(max_length=20, unique=True, verbose_name='RA')),
                ('password', models.CharField(max_length=55, verbose_name='Senha')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['firstName', 'lastName'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='idTaskType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Task_Type'),
        ),
        migrations.AddField(
            model_name='class',
            name='idProfessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
    ]
