# Generated by Django 2.0.2 on 2018-03-22 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='idStudent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='task',
            name='idTaskType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Task_Type'),
        ),
        migrations.AddField(
            model_name='class',
            name='idProfessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
    ]
