# Generated by Django 2.0.2 on 2018-04-04 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professors', '0001_initial'),
        ('students', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='idProfessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.Professor'),
        ),
        migrations.AddField(
            model_name='class',
            name='idStudent',
            field=models.ManyToManyField(related_name='Alunos', to='students.Student'),
        ),
    ]
