# Generated by Django 2.0.2 on 2018-05-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180503_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
    ]
