# Generated by Django 2.0.2 on 2018-03-23 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.User')),
                ('graduationType', models.CharField(choices=[('B', 'Bacharel'), ('D', 'Doutor'), ('M', 'Mestre')], max_length=1, verbose_name='Graduação')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
            bases=('core.user',),
        ),
    ]
